apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: zipkin
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 9411
      targetPort: 9411
      protocol: TCP
      name: http
  selector:
    app: zipkin
