
version: '3'
services:
  api-gateway-container:
    image: jacoboossag/api-gateway:dev
    ports:
      - 8080:8080
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=api-gateway-container
  proxy-client-container:
    image: jacoboossag/proxy-client:dev
    ports:
      - 8900:8900
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=proxy-client-container
  order-service-container:
    image: jacoboossag/order-service:dev
    ports:
      - 8300:8300
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=order-service-container
  payment-service-container:
    image: jacoboossag/payment-service:dev
    ports:
      - 8400:8400
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=payment-service-container
  product-service-container:
    image: jacoboossag/product-service:dev
    ports:
      - 8500:8500
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=product-service-container
  shipping-service-container:
    image: jacoboossag/shipping-service:dev
    ports:
      - 8600:8600
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=shipping-service-container
  user-service-container:
    image: jacoboossag/user-service:dev
    ports:
      - 8700:8700
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=user-service-container
  favourite-service-container:
    image: jacoboossag/favourite-service:dev
    ports:
      - 8800:8800
    networks:
      - microservices_network
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      - EUREKA_CLIENT_REGION=default
      - EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT=myzone
      - EUREKA_CLIENT_SERVICEURL_MYZONE=http://service-discovery-container:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-discovery-container:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://cloud-config-container:9296/
      - EUREKA_INSTANCE=favourite-service-container

networks:
  microservices_network:
    driver: bridge

