apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: service-discovery
  ports:
    - port: 8761
      targetPort: 8761
  type: LoadBalancer
