apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: microservices
  labels:
    app: proxy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
        - name: proxy-client
          image: jacoboossag/proxy-client:dev
          ports:
            - containerPort: 8900
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin-service:9411"

            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"

            # ✅ InstanceId único por Pod (ideal en K8s)
            - name: EUREKA_INSTANCE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            # ✅ Garantiza que Eureka use IP
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

            - name: SPRING_APPLICATION_NAME
              value: "PROXY-CLIENT"

            - name: SERVER_PORT
              value: "8900"

            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/proxy-client"

          livenessProbe:
            httpGet:
              path: /proxy-client/actuator/health
              port: 8900
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /proxy-client/actuator/health
              port: 8900
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 3

          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config