apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  namespace: microservices
  labels:
    app: favourite-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      containers:
        - name: favourite-service
          image: jacoboossag/favourite-service:dev
          ports:
            - containerPort: 8800
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"

            # Application Name (used by Eureka)
            - name: SPRING_APPLICATION_NAME
              value: "FAVOURITE-SERVICE"

            # Zipkin
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin-service:9411"

            # Cloud Config Server
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"

            # Eureka Discovery
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"

            # Registers Pod IP as instance hostname (required by your config repo)
            - name: EUREKA_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

            # Spring Boot Context
            - name: SERVER_PORT
              value: "8800"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/favourite-service"

          livenessProbe:
            httpGet:
              path: /favourite-service/actuator/health/liveness
              port: 8800
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /favourite-service/actuator/health/readiness
              port: 8800
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5

          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config
