apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: jacoboossag/payment-service:dev
          ports:
            - containerPort: 8400
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin-service:9411"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://cloud-config:9296"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"

            # ⬇️ Eureka registrará instancia usando IP del Pod
            - name: EUREKA_INSTANCE_INSTANCE_ID
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

            # ⬇️ Garantiza que use IP y no hostname
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"

            - name: SPRING_APPLICATION_NAME
              value: "PAYMENT-SERVICE"
            - name: SERVER_PORT
              value: "8400"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/payment-service"

          livenessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /payment-service/actuator/health
              port: 8400
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: common-config-volume
              mountPath: /app/config
      volumes:
        - name: common-config-volume
          configMap:
            name: common-config